version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: nodevault-mongodb-compose
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb-data:/data/db
    networks:
      - nodevault-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/nodevault --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: talhamemon12/nodevault-app:latest
    container_name: nodevault-app-compose
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    volumes:
      - app-backups:/app/backups
    networks:
      - nodevault-network
    command: ["node", "main.js"]

networks:
  nodevault-network:
    driver: bridge

volumes:
  mongodb-data:
    external: true
    name: mongodb-persistent-data

  app-backups:
